insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Denys bio', '2007-12-03 10:15:30', current_date, 'denys@gmail.com', true, 'location', 'Denys D.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'denys', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Kirill bio', '2007-12-03 10:15:30', current_date, 'kirill@gmail.com', true, 'location', 'Kirill K.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'kirill', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Anton bio', '2007-12-03 10:15:30', current_date, 'anton@gmail.com', true, 'location', 'Anton A.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'anton', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Taras bio', '2007-12-03 10:15:30', current_date, 'taras@gmail.com', true, 'location', 'Taras T.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'taras', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Leonid bio', '2007-12-03 10:15:30', current_date, 'leonid@gmail.com', true, 'location', 'Leonid L.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'leonid', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Mihail bio', '2007-12-03 10:15:30', current_date, 'mihail@gmail.com', true, 'location', 'Mihail M.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'mihail', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Maria bio', '2007-12-03 10:15:30', current_date, 'maria@gmail.com', true, 'location', 'Maria M.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'maria', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Pedro bio', '2007-12-03 10:15:30', current_date, 'perdo@gmail.com', true, 'location', 'Pedro P.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'pedro', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Huan bio', '2007-12-03 10:15:30', current_date, 'huan@gmail.com', true, 'location', 'Huan H.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'huan', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Aleksei bio', '2007-12-03 10:15:30', current_date, 'aleksei@gmail.com', true, 'location', 'Aleksei A.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'aleksei', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Aleksandr bio', '2007-12-03 10:15:30', current_date, 'aleksandr@gmail.com', true, 'location', 'Aleksandr A.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'aleksandr', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Svetlana bio', '2007-12-03 10:15:30', current_date, 'svetlana@gmail.com', true, 'location', 'Svetlana S.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'svetlana', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Pavel bio', '2007-12-03 10:15:30', current_date, 'pavel@gmail.com', true, 'location', 'Pavel P.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'pavel', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Oksana bio', '2007-12-03 10:15:30', current_date, 'oksana@gmail.com', true, 'location', 'Oksana O.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'oksana', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Ilona bio', '2007-12-03 10:15:30', current_date, 'ilona@gmail.com', true, 'location', 'Ilona I.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'ilona', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Valeriya bio', '2007-12-03 10:15:30', current_date, 'valeriya@gmail.com', true, 'location', 'Valeriya V.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'valeriya', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Tatyana bio', '2007-12-03 10:15:30', current_date, 'tatyana@gmail.com', true, 'location', 'Tatyana T.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'tatyana', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Angelina bio', '2007-12-03 10:15:30', current_date, 'angelina@gmail.com', true, 'location', 'Angelina A.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'angelina', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Nadezhda bio', '2007-12-03 10:15:30', current_date, 'nadezhda@gmail.com', true, 'location', 'Nadezhda N.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'nadezhda', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Varvara bio', '2007-12-03 10:15:30', current_date, 'varvara@gmail.com', true, 'location', 'Varvara V.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'varvara', 'website');
insert into users (bio, birth_date, created_date, email_address, is_enabled, location, name, password, profile_background_image, profile_image, username, website) values ('Vladlena bio', '2007-12-03 10:15:30', current_date, 'vladlena@gmail.com', true, 'location', 'Vladlena V.', '$2a$10$FgDVYsJxJNu6CCwpprnnKOkT8by0Uf9aX6q5MNdh/LA6qc80spZ86', 'image', 'image',  'vladlena', 'website');


insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, 'Original post for user 1', 1, null);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, 'Another original post for user 1', 1, null);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, 'Reply to post1 from user2', 2, 1);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, 'Reply to post1 from user4', 4, 1);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, null, 3, 1);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, null, 2, 2);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, 'Original post from user2', 2, null);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, 'Original post from user3', 3, null);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, 'Another original post from user3', 3, null);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, 'Another original post from user2', 2, null);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, 'Retweet post 2 with comment for post 2 from user4', 4, 2);
insert into posts (created_date, image, text, user_id, original_post_id) values (current_date, null, null, 1, 7);


insert into follows values (1, 2);
insert into follows values (1, 3);
insert into follows values (1, 4);
insert into follows values (1, 5);
insert into follows values (1, 6);
insert into follows values (1, 7);
insert into follows values (1, 8);
insert into follows values (1, 9);
insert into follows values (1, 11);
insert into follows values (1, 12);
insert into follows values (1, 13);
insert into follows values (1, 14);
insert into follows values (1, 15);
insert into follows values (1, 16);
insert into follows values (3, 1);
insert into follows values (4, 1);
insert into follows values (5, 1);
insert into follows values (6, 1);
insert into follows values (7, 1);
insert into follows values (8, 1);

insert into bookmarks values (1, 1);
insert into bookmarks values (2, 1);
insert into bookmarks values (3, 1);
insert into bookmarks values (4, 1);
insert into bookmarks values (5, 1);
insert into bookmarks values (1, 2);
insert into bookmarks values (1, 3);
insert into bookmarks values (1, 4);
insert into bookmarks values (1, 5);
insert into bookmarks values (1, 6);
insert into bookmarks values (1, 7);
insert into bookmarks values (1, 8);
insert into bookmarks values (1, 9);
insert into bookmarks values (1, 10);

insert into likes values (1, 1);
insert into likes values (1, 2);
insert into likes values (1, 3);
insert into likes values (1, 4);
insert into likes values (1, 5);
insert into likes values (1, 6);
insert into likes values (1, 7);
insert into likes values (1, 8);
insert into likes values (1, 9);
insert into likes values (1, 10);

INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 2, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 3, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 4, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 5, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 6, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 7, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 8, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 9, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 11, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 12, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 13, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 14, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 15, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('FOLLOWER', CURRENT_DATE, 16, null, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('LIKE', CURRENT_DATE, 2, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('LIKE', CURRENT_DATE, 3, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('LIKE', CURRENT_DATE, 4, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('LIKE', CURRENT_DATE, 5, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('LIKE', CURRENT_DATE, 6, 1, 1);

INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('LIKE', CURRENT_DATE, 7, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('LIKE', CURRENT_DATE, 8, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('LIKE', CURRENT_DATE, 9, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('LIKE', CURRENT_DATE, 10, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('RETWEET', CURRENT_DATE, 2, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('RETWEET', CURRENT_DATE, 3, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('RETWEET', CURRENT_DATE, 4, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('RETWEET', CURRENT_DATE, 5, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('RETWEET', CURRENT_DATE, 6, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('RETWEET', CURRENT_DATE, 7, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('RETWEET', CURRENT_DATE, 8, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('RETWEET', CURRENT_DATE, 9, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('RETWEET', CURRENT_DATE, 10, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('REPLY', CURRENT_DATE, 2, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('REPLY', CURRENT_DATE, 3, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('REPLY', CURRENT_DATE, 4, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('REPLY', CURRENT_DATE, 5, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('REPLY', CURRENT_DATE, 6, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('REPLY', CURRENT_DATE, 7, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('REPLY', CURRENT_DATE, 8, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('REPLY', CURRENT_DATE, 9, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('REPLY', CURRENT_DATE, 10, 1, 1);
INSERT INTO NOTIFICATIONS (NOTIFICATION_TYPE, TIMESTAMP, INITIATOR, POST, RECIPIENT) VALUES ('ENTRANCE', CURRENT_DATE, null, null, 1);

insert into views values (1, 1);