###
POST localhost:8080/api/registration
Content-Type: application/json

{"username": "justdenys", "emailAddress": "denyaaquapark@gmail.com", "password": "141141141",
  "birthDate": "2003-02-02T16:25:24", "name": "Anton Bliz"}


###
PATCH localhost:8080/api/registration?token=9cb4e0e8-6868-4957-bda4-f61974cc1877

###
POST localhost:8080/api/login
Content-Type: application/json

{
  "emailAddress": "denys@gmail.com",
  "password": "1",
  "rememberMe": true
}

###
GET localhost:8080/api/users/p/4

###
POST localhost:8080/api/registration/save-user
Content-Type: application/json

{"username": "denys2", "emailAddress": "d.kozarenkoo@gmail.com", "password": "141"}


###
POST localhost:8080/api/login/authenticate
Content-Type: application/json

{
  "emailAddress": "denyaaquapark@gmail.com",
  "password": "141",
  "rememberMe": true
}

###
POST localhost:8080/api/posts
Authorization: Bearer token
Content-Type: application/json

{
  "user": {
    "id": 1
  }
}

###
POST localhost:8080/api/posts
Authorization: Bearer token
Content-Type: application/json

{
  "user": {
    "id": 1
  }
}

###
DELETE localhost:8080/api/posts/1

###
PATCH localhost:8080/api/posts
Content-Type: application/json

{
  "id": 1,
  "text": "Updated text",
  "image": "Updated image"
}

###
GET localhost:8080/api/posts/1/ret
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZW55cyIsImlhdCI6MTY4NDI1NTIyNCwiZXhwIjoxNjg1MTE5MjI0fQ.rXyUVoQ5Sl0DFlyd_gainAxt0f7fYZSwq5V40TmO8hxZY3bZYU_U0mCN1hjJMOC6iA9Bc-s6c0h_Lk1HKyckdA

###
POST localhost:8080/api/posts
Authorization: Bearer token
Content-Type: application/json

{
  "user": {
    "id": 1
  },
  "text": "Some text. Post",
  "image": "someImage"
}

###
GET localhost:8080/api/posts/1/replies
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZW55cyIsImlhdCI6MTY4NDI1ODU2NiwiZXhwIjoxNjg1MTIyNTY2fQ.THoa35b9F8sU4Y_XSZ-TOG2C-0xgPxIDt_K5hEYbFdepgnwTz7-ClTyeKe2vzPHGOUUwWp2sfFzkdz0C3kRpDA
###
POST localhost:8080/api/users/p/denys
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZW55cyIsImlhdCI6MTY4NDI1NDgxNywiZXhwIjoxNjg1MTE4ODE3fQ.0iuRCJTpjgGEwysb4i2Zm3Vu0O85ZopG_4S3phC-DRMAWocnwbflkOd7Jf31ngzLBmKhi4YLnMPy_zjP80n-1A


###
POST localhost:8080/api/posts/like
Authorization: Bearer token
Content-Type: application/json

{
  "user": {
    "id": 1
  },
  "post": {
    "id": 1
  }
}

###
GET localhost:8080/api/posts/1

###
POST localhost:8080/api/posts/bookmark
Content-Type: application/json

{
  "user": {
    "id": 1
  },
  "post": {
    "id": 1
  }
}

###
GET localhost:8080/api/posts?p=0&n=3