###
POST localhost:8080/registration/check-email
Content-Type: application/json

{"emailAddress": "d.kozarenkoo@gmail.com"}

###
POST localhost:8080/registration/check-username
Content-Type: application/json

{"username": "denys"}

###
POST localhost:8080/registration/register
Content-Type: application/json

// впишіть свою пошту
{"username": "denys", "emailAddress": "denyaaquapark@gmail.com", "password": "141"}

###
POST localhost:8080/login/authenticate
Content-Type: application/json

{"username": "denys", "password": "141", "rememberMe":  false}

